export type { Product } from "./types"
export { useGetProductsQuery } from "./get/getProducts"
export { useCreateProductMutation } from "./post/createProduct"
export { productApi } from "./productApi"
export { useGetProductVariantsQuery } from "./get/getProductVariants"
