export { PurchasePage } from "./PurchasePage/PurchasePage"
export { RealizationPage } from "./RealizationPage/RealizationPage"
export { DeliveryPage } from "./DeliveryPage/DeliveryPage"
export { RealizationHistoryPage } from "./RealizationHistoryPage/RealizationHistoryPage"
export { StatisticsPage } from "./StatisticsPage/StatisticsPage"
