export enum RealizationTags {
  REALIZATION_ITEMS = "REALIZATION_ITEMS",
  ACTIVE_REALIZATIONS = "ACTIVE_REALIZATIONS",
  REALIZATION_BY_ID = "REALIZATION_BY_ID",
  PACKAGE_REALIZATIONS = "PACKAGE_REALIZATIONS",
}

export const realizationTagsArray = Object.values(RealizationTags)
